USE [master]
GO

/****** Object:  Database [scn_xxx]    Script Date: 2015-07-30 12:48:51 PM ******/
CREATE DATABASE [scn_xxx]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'scn_xxx', FILENAME = N'D:\MSSQL\Data\scn_xxx.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'scn_xxx_log', FILENAME = N'D:\MSSQL\Logs\scn_xxx_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [scn_xxx] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [scn_xxx].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [scn_xxx] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [scn_xxx] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [scn_xxx] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [scn_xxx] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [scn_xxx] SET ARITHABORT OFF 
GO

ALTER DATABASE [scn_xxx] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [scn_xxx] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [scn_xxx] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [scn_xxx] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [scn_xxx] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [scn_xxx] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [scn_xxx] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [scn_xxx] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [scn_xxx] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [scn_xxx] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [scn_xxx] SET  DISABLE_BROKER 
GO

ALTER DATABASE [scn_xxx] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [scn_xxx] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [scn_xxx] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [scn_xxx] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [scn_xxx] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [scn_xxx] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [scn_xxx] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [scn_xxx] SET RECOVERY FULL 
GO

ALTER DATABASE [scn_xxx] SET  MULTI_USER 
GO

ALTER DATABASE [scn_xxx] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [scn_xxx] SET DB_CHAINING OFF 
GO

ALTER DATABASE [scn_xxx] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [scn_xxx] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [scn_xxx] SET  READ_WRITE 
GO


